import { Component, useEffect, useState } from "react";
import { BrowserRouter, NavLink, Route, Routes } from "react-router-dom";
import { Activity, AlertTriangle, BarChart3, Bell, Camera, ChevronDown, HelpCircle, LayoutDashboard, LogOut, Map, Search, Settings, Shield, Video } from "lucide-react";
import { API_BASE_URL, getAlerts, getAnalytics, getCameras, getDetections, getEvents, startStream, stopStream } from "./services/api";
import "./App.css";
import ZoneEditor from "./components/zones/ZoneEditor";
import useWebSocket from "./hooks/useWebSocket";

const nav = [["Dashboard", "/dashboard", LayoutDashboard], ["Live Monitoring", "/monitoring", Video], ["Alerts", "/alerts", Bell], ["Analytics", "/analytics", BarChart3], ["Archive", "/events", Activity], ["Cameras", "/cameras", Camera], ["Border Map", "/border-map", Map], ["Settings", "/settings", Settings]];
const asArray = (value) => { if (!Array.isArray(value)) throw new Error("Unexpected list response from the surveillance backend."); return value; };
const asObject = (value) => { if (!value || Array.isArray(value) || typeof value !== "object") throw new Error("Unexpected analytics response from the surveillance backend."); return value; };

function useRemote(loader, initial, normalize) {
  const [data, setData] = useState(initial); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [version, setVersion] = useState(0);
  useEffect(() => { let mounted = true; loader().then(normalize).then((value) => { if (mounted) setData(value); }).catch((err) => { if (mounted) setError(err.message || "Unable to load surveillance data."); }).finally(() => { if (mounted) setLoading(false); }); return () => { mounted = false; }; }, [loader, normalize, version]);
  function reload() { setLoading(true); setError(null); setVersion((current) => current + 1); }
  return { data, loading, error, reload };
}

class RouteErrorBoundary extends Component {
  state = { failed: false };
  static getDerivedStateFromError() { return { failed: true }; }
  render() { return this.state.failed ? <div className="fatal-state"><AlertTriangle size={22} /><div><b>Unable to render this operational view.</b><span>Refresh the page to try again.</span></div></div> : this.props.children; }
}

function Header() { return <header className="topbar"><div className="mobile-logo">SENTINEL AI</div><div className="system-pill"><i /> SYSTEM STATUS</div><div className="header-search"><Search size={16} /> Search alerts, events...</div><div className="header-tools"><Settings size={19} /><HelpCircle size={19} /><span className="notification"><Bell size={19} /><b /></span><div className="avatar">OP</div><ChevronDown size={15} /></div></header>; }
function Sidebar() { return <aside className="sidebar"><div className="brand"><div className="brand-mark"><Shield size={22} /></div><div><strong>Sentinel AI</strong><small>Border Control Unit</small></div></div><nav>{nav.map(([label, path, Icon]) => <NavLink key={path} to={path} className={({ isActive }) => isActive ? "active" : ""}><Icon size={19} /><span>{label}</span></NavLink>)}</nav><div className="sidebar-foot"><NavLink to="/login"><LogOut size={19} /><span>Log Out</span></NavLink><small>Operator Profile</small></div></aside>; }
function Shell({ children }) { return <div className="app-shell"><Sidebar /><div className="main"><Header />{children}</div></div>; }
function PageHead({ eyebrow, title, sub }) { return <div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{sub && <p>{sub}</p>}</div></div>; }
function State({ loading, error, empty, children, reload }) { if (loading) return <div className="state"><div className="spinner" /> Loading operational data...</div>; if (error) return <div className="state error-state"><AlertTriangle size={18} /><span>{error}</span>{reload && <button className="retry-btn" onClick={reload}>Retry</button>}</div>; if (empty) return <div className="state">{empty}</div>; return children; }
function Stat({ label, value, detail, tone = "" }) { return <div className={`stat ${tone}`}><span>{label}</span><strong>{value ?? "Unavailable"}</strong>{detail && <small>{detail}</small>}</div>; }
function CameraTile({ camera }) { const status = camera.status || (camera.is_active ? "online" : "offline"); const active = status === "online"; return <div className="camera-tile"><div className="camera-feed">{active ? <img className="camera-preview" src={`${API_BASE_URL}/api/streams/${camera.id}/mjpeg`} alt={`${camera.camera_code} live preview`} /> : <div className="camera-offline">OFFLINE / NO SIGNAL</div>}<div className="feed-top"><b>{camera.camera_code}</b><span className={active ? "live" : "down"}>{status.toUpperCase()}</span></div><div className="feed-bottom"><span>{camera.sector}</span><time>{camera.name}</time></div></div><div className="tile-meta"><div><b>{camera.name}</b><small>{camera.stream_url || "No stream source configured"}</small></div><span className={status}>{status}</span></div></div>; }

function Dashboard() { const cameras = useRemote(getCameras, [], asArray); const alerts = useRemote(getAlerts, [], asArray); const analytics = useRemote(getAnalytics, null, asObject); const { message, connected } = useWebSocket(); const liveAlerts = message?.type === "alert" && message.data ? [message.data, ...alerts.data.filter((alert) => alert.id !== message.data.id)] : alerts.data; const reload = () => { cameras.reload(); alerts.reload(); analytics.reload(); }; return <Shell><main className="content"><PageHead eyebrow="Monitoring Overview" title="Border Surveillance" sub={`Real-time intelligence from configured surveillance sources. Live alerts: ${connected ? "connected" : "REST fallback"}.`} /><State loading={cameras.loading || alerts.loading || analytics.loading} error={cameras.error || alerts.error || analytics.error} reload={reload}><div className="stats"><Stat label="ACTIVE CAMERAS" value={cameras.data.filter((camera) => camera.is_active).length} /><Stat label="ACTIVE ALERTS" value={analytics.data?.active_alerts} tone="critical" /><Stat label="PEOPLE DETECTED" value="Unavailable" detail="Object totals are not provided by the backend" /><Stat label="VEHICLES" value="Unavailable" detail="Object totals are not provided by the backend" /><Stat label="SYSTEM HEALTH" value="Unavailable" detail="No health metric endpoint" /></div><div className="dashboard-grid"><section><div className="section-title"><div><h2>Live Surveillance</h2><small>Configured camera sources</small></div><span className="tag blue">{cameras.data.length} SOURCES</span></div><State empty={cameras.data.length ? null : "No cameras configured. Add a camera source to begin surveillance."}><div className="camera-grid">{cameras.data.map((camera) => <CameraTile key={camera.id} camera={camera} />)}</div></State></section><section className="alert-panel"><div className="panel-title"><h2><AlertTriangle size={18} /> Active Alerts</h2><span className="tag salmon">{liveAlerts.length}</span></div><State empty={liveAlerts.length ? null : "No active alerts"}>{liveAlerts.slice(0, 4).map((alert) => <div className="alert-item" key={`${alert.id}-${alert.timestamp || alert.created_at || "live"}`}><div className="alert-row"><b>{alert.severity || "Unknown"}</b><time>{alert.timestamp || alert.created_at || "Unavailable"}</time></div><p>{alert.reason || alert.message || "No description"}</p><code>{alert.zone || "Zone unavailable"}</code></div>)}</State></section></div></State></main></Shell>; }
function Alerts() { const result = useRemote(getAlerts, [], asArray); return <Shell><main className="content"><PageHead eyebrow="Incident Response" title="Active Alerts" sub="Alerts returned by the surveillance backend." /><State {...result} empty={result.data.length ? null : "No active alerts"}><div className="table-wrap"><table><thead><tr><th>ID</th><th>SEVERITY</th><th>EVENT</th><th>SOURCE</th><th>TRACK / OBJECT</th><th>ZONE / SCORE</th><th>TIMESTAMP</th><th>EVIDENCE</th></tr></thead><tbody>{result.data.map((alert) => <tr key={alert.id}><td>{alert.id}</td><td><span className={`severity ${(alert.severity || "unknown").toLowerCase()}`}>{alert.severity || "Unknown"}</span></td><td><strong>{alert.reason || alert.message || "No description"}</strong></td><td>{alert.camera_id ?? "Unavailable"}</td><td>{alert.track_id ?? "Unavailable"} / {alert.object_type || "Unavailable"}</td><td>{alert.zone || "Unavailable"} / {alert.score ?? "-"}</td><td>{alert.timestamp || alert.created_at || "Unavailable"}</td><td>{alert.evidence_path ? <a href={`http://127.0.0.1:8000${alert.evidence_path}`} target="_blank" rel="noreferrer">Open</a> : "Unavailable"}</td></tr>)}</tbody></table></div></State></main></Shell>; }
function Cameras() { const result = useRemote(getCameras, [], asArray); return <Shell><main className="content"><PageHead eyebrow="Network Infrastructure" title="Border Cameras" sub="Manage configured network streams and detection endpoints." /><State {...result} empty={result.data.length ? null : "No cameras configured. Add a camera source to begin surveillance."}><div className="stats four"><Stat label="TOTAL CAMERAS" value={result.data.length} /><Stat label="ONLINE" value={result.data.filter((camera) => (camera.status || (camera.is_active ? "online" : "offline")) === "online").length} /><Stat label="OFFLINE / DEGRADED" value={result.data.filter((camera) => !camera.is_active || camera.status === "offline").length} tone="critical" /><Stat label="AI ACTIVE NODES" value="Unavailable" detail="No node metric endpoint" /></div><div className="table-wrap"><table><thead><tr><th>CAMERA ID</th><th>NAME / LOCATION</th><th>SECTOR</th><th>STATUS</th><th>SOURCE</th><th>DETECTION</th></tr></thead><tbody>{result.data.map((camera) => <tr key={camera.id}><td>{camera.camera_code}</td><td>{camera.name}</td><td>{camera.sector}</td><td>{camera.status || (camera.is_active ? "online" : "offline")}</td><td>{camera.stream_url || "Not configured"}</td><td><span className="tag blue">{camera.is_active ? "ENABLED" : "DISABLED"}</span></td></tr>)}</tbody></table></div></State></main></Shell>; }
function Events() { const result = useRemote(getEvents, [], asArray); return <Shell><main className="content"><PageHead eyebrow="Historical Intelligence" title="Event Archive" sub="Recorded events returned by the surveillance backend." /><State {...result} empty={result.data.length ? null : "No events recorded"}><div className="table-wrap"><table><thead><tr><th>EVENT ID</th><th>TYPE</th><th>CAMERA</th><th>SEVERITY</th><th>DESCRIPTION</th><th>TIMESTAMP</th></tr></thead><tbody>{result.data.map((event) => <tr key={event.id}><td>{event.id}</td><td>{event.event_type || "Unavailable"}</td><td>{event.camera_id ?? "Unavailable"}</td><td>{event.severity || "Unavailable"}</td><td>{event.description || "No description"}</td><td>{event.timestamp || "Unavailable"}</td></tr>)}</tbody></table></div></State></main></Shell>; }
function Analytics() { const result = useRemote(getAnalytics, null, asObject); const detections = useRemote(getDetections, [], asArray); const reload = () => { result.reload(); detections.reload(); }; const analytics = result.data || {}; return <Shell><main className="content"><PageHead eyebrow="Operational Intelligence" title="Security Analytics" sub="Metrics calculated from stored detections, alerts, and events." /><State loading={result.loading || detections.loading} error={result.error || detections.error} reload={reload} empty={result.data ? null : "Analytics data unavailable"}><div className="stats four"><Stat label="TOTAL DETECTIONS" value={analytics.total_detections ?? "Unavailable"} /><Stat label="ACTIVE ALERTS" value={analytics.active_alerts ?? "Unavailable"} tone="critical" /><Stat label="CRITICAL ALERTS" value={analytics.critical_alerts ?? "Unavailable"} /><Stat label="TOTAL EVENTS" value={analytics.total_events ?? "Unavailable"} /></div><div className="chart-grid"><Chart title="Detection Trends" count={detections.data.length} /><Chart title="Alert Distribution" count={analytics.critical_alerts} /><Chart title="Stored Activity" count={analytics.total_events} /></div></State></main></Shell>; }
function Chart({ title, count }) { return <section className="chart panel"><h2>{title}</h2>{Number.isFinite(count) && count > 0 ? <div className="chart-value">{count}<small> records available</small></div> : <div className="chart-placeholder">No data available</div>}</section>; }
function Monitoring() { const result = useRemote(getCameras, [], asArray); const [selectedCameraId, setSelectedCameraId] = useState(""); const [streamingId, setStreamingId] = useState(null); const [streamError, setStreamError] = useState(null); const selectedCamera = result.data.find((camera) => camera.id === Number(selectedCameraId)) || result.data[0]; const status = selectedCamera?.status || (selectedCamera?.is_active ? "online" : "offline"); const previewActive = selectedCamera && (streamingId === selectedCamera.id || status === "online"); async function toggleStream() { if (!selectedCamera) return; setStreamError(null); try { if (previewActive) { await stopStream(selectedCamera.id); setStreamingId(null); } else { await startStream(selectedCamera.id); setStreamingId(selectedCamera.id); } } catch (error) { setStreamError(error.message); } } return <Shell><main className="content"><PageHead eyebrow="Live Monitoring" title="Camera Feed" sub="Select a configured camera to inspect its stream and configure its restricted zones." /><State {...result} empty={result.data.length ? null : "No cameras configured. Add a video source before starting monitoring."}>{selectedCamera && <><div className="monitor-grid"><div className="big-feed">{previewActive ? <img className="camera-preview" src={`${API_BASE_URL}/api/streams/${selectedCamera.id}/mjpeg`} alt={`${selectedCamera.camera_code} live preview`} /> : <div className="camera-offline">OFFLINE / NO SIGNAL</div>}<div className="feed-top"><b>{selectedCamera.camera_code}</b><span className={previewActive ? "live" : "down"}>{previewActive ? "LIVE" : status.toUpperCase()}</span></div><div className="feed-bottom"><span>{selectedCamera.stream_url || "No stream source configured"}</span></div></div><div className="panel monitor-controls"><h2>Camera Selection</h2><select value={selectedCamera.id} onChange={(event) => { setSelectedCameraId(event.target.value); setStreamingId(null); }}>{result.data.map((camera) => <option value={camera.id} key={camera.id}>{camera.camera_code} - {camera.name}</option>)}</select><button className="primary" onClick={toggleStream}>{previewActive ? "Stop Stream" : "Start Stream"}</button><p className="state">{streamError || (previewActive ? "Processed video with detection overlays is active." : "Start the stream to open this camera source.")}</p></div></div><ZoneEditor cameras={result.data} cameraId={selectedCamera.id} onCameraChange={(value) => { setSelectedCameraId(value); setStreamingId(null); }} previewActive={previewActive} /></>}</State></main></Shell>; }
function BorderMap() { const result = useRemote(getCameras, [], asArray); const mapped = result.data.filter((camera) => camera.location_lat != null && camera.location_lng != null); return <Shell><main className="content"><PageHead eyebrow="Geospatial Operations" title="Border Map" sub="Configured camera positions and restricted zones." /><State {...result} empty={mapped.length ? null : "Map data unavailable. Configure camera coordinates to display operational positions."}><div className="map-canvas">{mapped.map((camera, index) => <div className={`sensor map-sensor-${index}`} key={camera.id}>o<small>{camera.camera_code}</small></div>)}<div className="map-legend"><b>Map Legend</b><span>o Configured Camera</span></div></div></State></main></Shell>; }
function SettingsPage() { return <Shell><main className="content"><PageHead eyebrow="System Administration" title="Configuration" sub="Local controls for detection sensitivity. These settings are UI-only until persistence is implemented." /><div className="settings-layout"><div className="settings-nav"><b>Detection Thresholds</b><span>Alert Config</span><span>Restricted Zones</span><span>Notification Settings</span><span>Operator Access</span></div><div><section className="settings-card"><h2>AI Sensitivity Calibration</h2><p>Adjust the confidence thresholds for local operator review. Values are not persisted by the current backend.</p><label>Human Detection Confidence<input type="range" /></label><label>Vehicle Identification<input type="range" /></label></section><section className="settings-card"><h2>Environmental Filters</h2><p>These controls are not persisted by the current backend.</p>{["Wildlife Suppression", "Severe Weather Compensation", "Night Vision Artifact Filtering"].map((name) => <div className="toggle-row" key={name}><span><b>{name}</b><small>UI-only configuration</small></span><i /></div>)}</section></div></div></main></Shell>; }
function Login() { return <div className="login"><Shield size={42} /><h1>Sentinel AI</h1><p>Border Control Unit</p><NavLink className="primary" to="/dashboard">Enter Command Center</NavLink></div>; }
export default function App() { return <RouteErrorBoundary><BrowserRouter><Routes><Route path="/login" element={<Login />} /><Route path="/" element={<Dashboard />} /><Route path="/dashboard" element={<Dashboard />} /><Route path="/monitoring" element={<Monitoring />} /><Route path="/alerts" element={<Alerts />} /><Route path="/events" element={<Events />} /><Route path="/archive" element={<Events />} /><Route path="/cameras" element={<Cameras />} /><Route path="/border-map" element={<BorderMap />} /><Route path="/analytics" element={<Analytics />} /><Route path="/settings" element={<SettingsPage />} /><Route path="*" element={<Dashboard />} /></Routes></BrowserRouter></RouteErrorBoundary>; }
